#!/usr/bin/env python3
"""
gen_docs.py - regenerates docs/ARCHITECTURE.md from the package sources (pure stdlib, nothing is imported/executed).

    python tools/gen_docs.py            # run again after you add / move modules
"""
import ast
import collections
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from layers import LAYERS  # noqa: E402

ROOT = os.environ.get("VISOLD_NEW") or os.path.dirname(HERE)
PKG = os.path.join(ROOT, "visold")
LEVEL = {c: i for i, grp in enumerate(LAYERS) for c in grp}

mods = {}
for dp, dn, fn in os.walk(PKG):
    dn[:] = sorted(d for d in dn if d != "__pycache__")
    for f in sorted(fn):
        if f.endswith(".py") and f != "__init__.py":
            p = os.path.join(dp, f)
            name = "visold." + os.path.relpath(p, PKG)[:-3].replace(os.sep, ".")
            text = open(p, encoding="utf-8").read()
            tree = ast.parse(text)
            doc = ast.get_docstring(tree) or ""
            m = re.search(r"Origin: visold_vsd_\.py (.+)", doc)
            defs, consts = [], 0
            for n in tree.body:
                if isinstance(n, ast.ClassDef):
                    defs.append(n.name)
                elif isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    defs.append(n.name + "()")
                elif isinstance(n, (ast.Assign, ast.AnnAssign)):
                    consts += 1
            deps = set()
            for n in tree.body:
                if isinstance(n, ast.ImportFrom) and (n.module or "").startswith("visold."):
                    deps.add(n.module)
            mods[name] = dict(lines=text.count("\n") + 1, origin=m.group(1).strip() if m else "-", defs=defs,
                              consts=consts, deps=deps)

ctxs = collections.OrderedDict()
for name in sorted(mods, key=lambda n: (LEVEL.get(n.split(".")[1], 99), n)):
    ctxs.setdefault(name.split(".")[1], []).append(name)


def ctx_purpose(c):
    p = os.path.join(PKG, c, "__init__.py")
    if os.path.exists(p):
        d = ast.get_docstring(ast.parse(open(p, encoding="utf-8").read())) or ""
        parts = d.split("\n\n", 1)
        return " ".join(parts[1].split()) if len(parts) > 1 else ""
    return ""


def public(defs, k=7):
    pub = [d for d in defs if not d.startswith("_")]
    shown = pub[:k]
    more = len(pub) - len(shown)
    return ", ".join("`%s`" % d for d in shown) + (" +%d more" % more if more > 0 else "") if shown else "-"


total = sum(m["lines"] for m in mods.values())
out = []
w = out.append
w("# Visold - Architecture (modular edition)")
w("")
w("*Generated by `tools/gen_docs.py` from the package sources - %d modules, %d bounded contexts, %s lines.*"
  % (len(mods), len(ctxs), format(total, ",")))
w("")
w("## 1. The idea in one paragraph")
w("")
w("The former 55,370-line `visold_vsd_.py` is now a package, `visold/`, organised by **bounded context** (domain), "
  "not by technical type. Every context sits on a **layer**; a module may import only from its own context or from "
  "a **lower** layer. Import cycles are therefore impossible, and each context can be read, tested and changed on its "
  "own. `visold_vsd_.py` is kept as the entry point and a flat-namespace facade, so `python visold_vsd_.py ...` and "
  "`from visold_vsd_ import Blockchain` still work. It contains no implementation and loads no legacy code.")
w("")
w("## 2. Layers and contexts (bottom to top)")
w("")
w("| Layer | Context | Purpose | Modules | Lines |")
w("|---:|---|---|---:|---:|")
for i, grp in enumerate(LAYERS):
    for c in grp:
        if c in ctxs:
            ms = ctxs[c]
            w("| L%d | `%s` | %s | %d | %s |" % (i, c, ctx_purpose(c).replace("|", "/"), len(ms),
                                              format(sum(mods[m]["lines"] for m in ms), ",")))
w("")
w("**Dependency rule:** `visold.<context>.*` may import `visold.<same context>.*` and any context on a lower layer - "
  "never a higher one. Enforced by `python tools/check_architecture.py` (also detects cycles, relative imports, "
  "imports of the facade, and names that do not exist).")
w("")
w("## 3. Where does X live?")
w("")
idx = {}
for name, m in mods.items():
    for d in m["defs"]:
        idx.setdefault(d.rstrip("()"), name)
KEY = ["Config", "Transaction", "Block", "Wallet", "Blockchain", "ConsensusEngine", "RoleManager", "Sequencer",
       "DifficultyEngine", "Storage", "BlockDatabase", "StateSnapshotEngine", "Mempool", "CommitRevealMempool",
       "StateEngine", "VVMEngine", "VVMAssembler", "Layer2State", "ProofRegistry", "GovernanceEngine", "P2PNetwork",
       "UDPTransport", "TLSManager", "ICEManager", "SPVClient", "ParallelMiner", "MiningEngine", "RPCServer",
       "IdentitySystem", "VisoldNode", "UserAccount", "SecurityGate", "SentinelNode", "CLI", "CLIHandler", "main",
       "TestSuite", "HardenedVerificationSuite", "SelfHealingOrchestrator", "RiskScoringEngine"]
w("| Name | Module |")
w("|---|---|")
for k in KEY:
    if k in idx:
        w("| `%s` | `%s` |" % (k, idx[k]))
w("")
w("Everything else: `grep -rn \"^class Name\\|^def name\" visold/` or see the module index below.")
w("")
w("## 4. Module index")
w("")
w("`Origin` = line range in the original monolith (for tracing and diffing against your old copy).")
for c, ms in ctxs.items():
    w("")
    w("### `%s` (layer L%d)" % (c, LEVEL.get(c, -1)))
    w("")
    w("| Module | Lines | Origin | Main definitions |")
    w("|---|---:|---|---|")
    for m in ms:
        w("| `%s` | %d | %s | %s |" % (m[len("visold."):], mods[m]["lines"], mods[m]["origin"].replace("|", "/"),
                                      public(mods[m]["defs"])))
w("")
w("## 5. Working with the package")
w("")
w("- **Add code** to the context that owns the concept. If it needs something from a higher layer, that is a design "
  "signal: pass it in as a parameter, or move the shared piece down.")
w("- **New module / context**: create the file, import what you need with absolute imports "
  "(`from visold.kernel.config import Config`), run `python tools/check_architecture.py`; for a new context add it to "
  "`tools/layers.py`. Then `python tools/gen_docs.py`.")
w("- **Never** import `visold_vsd_` from inside the package; it is the entry/facade only.")
w("- **Optional dependencies** (numpy, RocksDB, PostgreSQL, Redis, zstd, ...) are detected once in "
  "`visold.kernel.compat`; import the flags/modules from there.")
w("- **Logging** is configured once, on first import of `visold.kernel.logging_setup`; use "
  "`from visold.kernel.logging_setup import log`.")
w("")
w("## 6. Entry point")
w("")
w("`visold_vsd_.py` adds its own folder to `sys.path`, imports the public names of every module (historical flat "
  "namespace, in the original definition order), then runs the original `__main__` blocks unchanged "
  "(`--verify-hardened`, `--test-sc-name-1`, otherwise `visold.cli.entry.main()`). Keep `visold_vsd_.py` and the "
  "`visold/` folder side by side.")
w("")
os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
with open(os.path.join(ROOT, "docs", "ARCHITECTURE.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out))
print("docs/ARCHITECTURE.md written: %d modules, %d contexts" % (len(mods), len(ctxs)))
